[project]
name = "calculater-sharpe-and-profit-factor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorama>=0.4.6",
    "matplotlib>=3.10.8",
    "requests>=2.32.5",
    "retry>=0.9.2",
]
